import { type NextRequest, NextResponse } from "next/server"

// This is similar to Web API Controllers in ASP.NET
// GET /api/users
export async function GET(request: NextRequest) {
  // This would typically fetch from a database
  const users = [
    { id: 1, name: "John Doe", email: "john@example.com", role: "Admin" },
    { id: 2, name: "Jane Smith", email: "jane@example.com", role: "User" },
  ]

  return NextResponse.json(users)
}

// POST /api/users
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()

    // Validation (similar to model validation in ASP.NET)
    if (!body.name || !body.email) {
      return NextResponse.json({ error: "Name and email are required" }, { status: 400 })
    }

    // This would typically save to a database
    const newUser = {
      id: Date.now(), // In real app, this would be generated by DB
      name: body.name,
      email: body.email,
      role: body.role || "User",
    }

    return NextResponse.json(newUser, { status: 201 })
  } catch (error) {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 })
  }
}
